#ifndef __ENUM_H__
#define __ENUM_H__


typedef enum PlayerDrawType{
	STAND_RIGHT,
	STAND_LEFT,

	DASH_RIGHT_1,	DASH_RIGHT_2,	DASH_RIGHT_3,	DASH_RIGHT_4,	DASH_RIGHT_5,	DASH_RIGHT_6,
	DASH_LEFT_1,	DASH_LEFT_2,	DASH_LEFT_3,	DASH_LEFT_4,	DASH_LEFT_5,	DASH_LEFT_6,

	JUMP_RIGHT_1,	JUMP_RIGHT_2,
	JUMP_LEFT_1,	JUMP_LEFT_2,

	SHOT_RIGHT_1,	SHOT_RIGHT_2,
	SHOT_LEFT_1,	SHOT_LEFT_2,

	RAZER_RIGHT_1,	RAZER_RIGHT_2,	RAZER_RIGHT_3,
	RAZER_LEFT_1,	RAZER_LEFT_2,	RAZER_LEFT_3,

	DAMEGE_RIGHT_1,
	DAMEGE_LEFT_1,

	LAST_RIGHT_1, LAST_RIGHT_2,
	LAST_LEFT_1, LAST_LEFT_2
}PlayerDT;


typedef enum HitJudge{
	NOT_HIT,	HIT
}HitJ;


#endif